### PR TITLE
Removed redundant link formatting

### PR DESCRIPTION
**Pull request by hook321**

### CODE REVIEW

**Comment by maxnz** [comment]
@virtuald When I was adding these links, I was just following the format I saw on other links on the FIRSTwiki. Are the quoted parts actually necessary?

**Comment by virtuald** [comment]
Referring to a markdown guide... https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links

It appears the quotes are the 'title' of the link... which usually is what shows up when you hover over a link. So, they're optional. Typically the content inside the quotes will be different than that outside the quotes, otherwise they are redundant (as mentioned by this PR).

**Comment by hook321** [comment]
It might be simpler to just go through and remove these automatically with some regex magic.

**Comment by maxnz** [comment]
If you can do that, that would be great.

**Comment by hook321** [comment]
@maxnz I'll do that soon... Hopefully... Also, check the gitter chat, I'm gonna post something there in a minute or 2.

**Pull request merged**
