### PR TITLE
Try just deleting FIRST Frenzy, see if that's the only issue

### PR DESCRIPTION
**Pull request by devyntk**

### CODE REVIEW

**Comment by virtuald** [comment]
What's the problem you're running into?

**Comment by devyntk** [comment]
I assume you're also getting the same emails, but Github is saying the page if failing to regenerate. Here's the exact email:

> The page build failed with the following error:
> 
> Page build failed. For more information, see https://help.github.com/articles/troubleshooting-github-pages-build-failures.
> 
> For information on troubleshooting Jekyll see:
> 
>  https://help.github.com/articles/troubleshooting-jekyll-builds
> 
> If you have any questions you can contact us by replying to this email.

**Comment by virtuald** [comment]
Hm, I'm not getting the build email.

**Comment by devyntk** [comment]
This is my third attempt, and I think it has something to do with escaping a `:` in a page title. I'm just trying to delete that file now to see if that's the issue. I'm on my laptop, and I can't run the server on here (school issued).

**Comment by virtuald** [comment]
I just built everything locally, it seems to work fine here. Travis also runs a build... it's supposed to protect against this sort of thing. :)

Might be a jekyll version thing though... I was having issues with the latest version on travis.

**Comment by devyntk** [comment]
hmm. Still got that email, still with no error. I assume it's malformed Markdown somewhere, but I can't see where. Earlier, it explicitly said, both in the email and in the check where the error was, but now it's giving me nothing.

**Comment by virtuald** [comment]
Have you deleted the email?

**Comment by devyntk** [comment]
No.

**Comment by virtuald** [comment]
I'll upgrade jekyll locally and see if I run into the error, one sec.

**Comment by virtuald** [comment]
No errors locally here. Must be something weird. Did the other email have a more specific error message than the one you pasted above?

**Comment by devyntk** [comment]
The other one had something about a mapping value not allowed in this context in the FIRST_Frenzy.md file, but that’s not deleted, which is what I was testing earlier.

**Pull request merged**
